### PR TITLE
Custom root namespaces

### PR DESCRIPTION
**Pull request by lorenh**
Here's just a first quick attempt at adding custom root namespaces, I'm sure you can improve upon it, but it seems to work for my needs at the moment.

### CODE REVIEW

**Comment by airbreather** [comment]
Overall this is a good approach; I have nitpicks, but I would happily resolve those on my own.

The reasons why I'm sitting on this for a bit are because I want to:
1. Make it as clear as we can, at the level of the model, that the prefix is supposed to be unique within a particular write, never clashing with other prefixes
1. Have the model enforce the same rules that XML expects, so that failures should almost always happen before you get the opportunity to try writing your data, e.g., "duplicate prefix", "namespace is not a URI"
1. Consider options for preserving the root namespaces on read, for a better round-trip experience

For the first two, I think modeling it as `Dictionary<string, Uri>` is probably good enough, but that last bullet point is what's been keeping me from starting on it myself for the past couple of days or so until I get some time to sit down and think about the implications of putting it on `GpxMetadata`.

**Comment by lorenh** [comment]
I like the dictionary approach, and have made that change (in anticipation that it will likely be closer to what you come up with) I was trying to guess "what would Joe do?" since I saw hard classes being used in most other places.

**Comment by lorenh** [comment]
Any chance of getting this in sometime?  Would love to abandon my custom build of this library.

**Comment by airbreather** [comment]
> Any chance of getting this in sometime? Would love to abandon my custom build of this library.

Gonna be honest, this completely slipped my mind, and the "Pull Requests (1)" wasn't enough to make me remember.  Thanks for the ping.

I'll merge what you have here now, and then try to see if I can do any better with it after.

Thanks for the contribution.

**Pull request merged**
